# Generated by Django 6.0.6 on 2026-07-01 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['user', '-created_at'], name='skills_skil_user_id_1ea1ee_idx'),
        ),
    ]
