# Generated by Django 6.0.6 on 2026-07-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_skills_skil_user_id_1ea1ee_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='goal_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='started_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
