# Generated by Django 6.0.6 on 2026-07-07 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streak',
            old_name='last_active_date',
            new_name='last_activity_date',
        ),
        migrations.AddField(
            model_name='streak',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
