# Generated by Django 6.0.6 on 2026-07-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_adminfeedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminfeedback',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='adminfeedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='adminfeedback',
            name='subject',
            field=models.CharField(blank=True, default='General Feedback', max_length=255),
        ),
    ]
