# Generated by Django 6.0.6 on 2026-07-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_backuplog_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
