# Generated by Django 6.0.6 on 2026-07-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
